#!/usr/bin/with-contenv bash

s6-setuidgid "${TRTL_USER}" "TurtleCoind" \
  --rpc-bind-ip "0.0.0.0" \
  --data-dir "${TRTL_HOME}/blockchain" \
  --db-threads 5 \
  --log-file "${TRTL_HOME}/TurtleCoind.log" \
  --load-checkpoints "${TRTL_HOME}/checkpoints.csv" \
  --fee-amount "${NODE_FEE:-0}" \
  --fee-address "${WALLET_ADDRESS:-}"
