#!/usr/bin/env bash

if [ -f ./setup ]
then
  source setup
fi

echo "### TurtleCoin Node ###"
echo "Fee: ${FEE_AMOUNT} shells"
echo "Wallet address: ${WALLET_ADDRESS}"

exec "${TRTL_PATH}/TurtleCoind" \
  --rpc-bind-ip "${BIND_IP}" \
  --fee-amount "${FEE_AMOUNT}" \
  --fee-address "${WALLET_ADDRESS}"
